export const CreditActionType = {
  SET_CREDIT_PURPOSE: "SET_CREDIT_PURPOSE",
  SET_PROPERTY_VALUE: "SET_PROPERTY_VALUE",
  SET_INITIAL_PAYMENT: "SET_INITIAL_PAYMENT",
  SET_PERIOD: "SET_PERIOD",
  SET_MATERNAL_CAPITAL: "SET_MATERNAL_CAPITAL",
  SET_INSURANCE_CAR: "SET_INSURANCE_CAR",
  SET_INSURANCE_LIFE: "SET_INSURANCE_LIFE",
  SET_INITIAL_STATE: "SET_INITIAL_STATE",
};
